### ISSUE TITLE
Error message of invalid feature

### ISSUE THREAD

**Issue by YingX97** [fabilab/cell_atlas_approximations_API#15]
Hi Fabio,
Q: "What are the sequences of COL1A1,CD19,HELLO?"

here is what I got from the API error:
{
  "message": "Feature could not be found: {exc.feature}.",
    "error": {
      "type": "invalid_parameter",
      "invalid_parameter": "feature",
      "invalid_value": "HELLO"
  }
}

What does the {exc.features} means in the error message? Is there a way to put the exact invalid values into the message string?

cheers,

**Comment by iosonofabio** [comment]
Fixed in 41347eb, just a missing "f" in one line of code. Will be better in the next release, meanwhile you can do without since you are not parsing the human message anyway. Closing.
