### ISSUE TITLE
marker genes of invalid organ

### ISSUE THREAD

**Issue by YingX97** [fabilab/cell_atlas_approximations_API#16]
Hi Fabio,

Q: "Show 10 markers of AT1 in human brain".

I got an internal server error when calling the markers api for invalid organ:

https://api.atlasapprox.org/v1/markers?organism=h_sapiens&organ=brain&celltype=AT1&number=10&measurement_type=gene_expression

**Comment by iosonofabio** [comment]
thanks, yes it was a copy-paste bug in the data models. It's fixed in 9bfd7a5, will take 10-15 minutes to get deployed on lightsail
