### ISSUE TITLE
Wrong spelling of "gene expression" in neighborhood api

### ISSUE THREAD

**Issue by YingX97** [fabilab/cell_atlas_approximations_API#17]
Hi Fabio,

Can you please fix the spelling of the measurement type. Thanks.

// NEIGHBORHOOD
async function neighborhood({ organism, organ, measurement_type = "gene_expresion", include_embedding = false }) {
  let params = { organism, organ, measurement_type, include_embedding };
  return await _callEndpoint("neighborhood", params=params);
};

**Comment by iosonofabio** [comment]
Thank you, fixed in 0.2.3.
