### ISSUE TITLE
Marker genes with chromatin accessibility

### ISSUE THREAD

**Issue by YingX97** [fabilab/cell_atlas_approximations_API#20]
Hi Fabio,

Q: Show the 10 top marker peaks for schwann in h_sapiens nerve.

There is a 500 internal error when using the API for markers with chromatin accessibility at this URL:
https://api.atlasapprox.org/v1/markers?organism=h_sapiens&organ=thyroid&celltype=schwann&number=10&measurement_type=chromatin_accessibility.

and 400 error when using node.js

**Comment by iosonofabio** [comment]
This is confirmed and due to data quantisation, I'm trying to fix it

**Comment by iosonofabio** [comment]
fixed, next release
