### ISSUE TITLE
500 error for fly markers

### ISSUE THREAD

**Issue by YingX97** [fabilab/cell_atlas_approximations_API#21]
Hi Fabio,

Q: Show 10 markers of adipocyte in d_melanogaster fat

**Comment by YingX97** [comment]
These organs / celltypes don't work &                 work

1. oenocyte ❌ epithelial, oenocyte)                       ✓ muscle
2. fat ❌ epithelial, hemocyte)
3. trachea ❌ tracheocyte, neuron, muscle)          ✓ adipocyte
4. gut ❌ enteroendocrine)                                      ✓ enterocyte, stem
5. wing ❌ neuron, muscle)                                     ✓  glial
6. male_reproductive ❌ neuron).                           ✓ epithelial

**Comment by iosonofabio** [comment]
fixed, next release
