### ISSUE TITLE
No markers available in h miamia whole 

### ISSUE THREAD

**Issue by YingX97** [fabilab/cell_atlas_approximations_API#22]
Q: "Show 10 markers of diffuse endo in h_miamia whole"

params = {
  organism: "h_miamia", 
  organ: "whole", 
  celltype: "diffuse endo", 
  number: 10, 
  measurement_type: "gene_expression"
}
Result: 
markers:[ ]

**Comment by iosonofabio** [comment]
bug found and fixed, next release
