### ISSUE TITLE
Show markers for all cell types

### ISSUE THREAD

**Issue by YingX97** [fabilab/cell_atlas_approximations_API#24]
Catherine suggested enabling users to query and retrieve all markers associated with specific cell types, both in textual and dot plot formats, during our lab meeting.

**Comment by iosonofabio** [comment]
deployed in version 63 (today, evening). You can use the magic string "all" to request markers for all cell types (takes around 2 seconds backend time at present). The returned dict will have an additional key, "targets", which can be safely ignored for now but might be useful in the future.

**Comment by iosonofabio** [comment]
Note: A question that works NLP-wise is the following: "What are 3 markers for all cells in human lung?"

edit: and you don't need to update the NLP, the latest version from this morning will work automatically.
