### ISSUE TITLE
Invalid target gene from interactors api call

### ISSUE THREAD

**Issue by YingX97** [fabilab/cell_atlas_approximations_API#28]
Hi Fabio,

Q1: What are the interactors of COL1A1 in human lung?
Q2: Show interactors of PDGFRA in human lung
One of the returned interactors for both queries, "TGFB1," is invalid for the human data. Is this something we need to be concerned about? Or can I just exclude the invalid gene when making the plot?"

Node:
> params = {organism:'h_sapiens',organ:'lung', features: 'COL1A1'}
> await api.interaction_partners(params)
> dotplot_params = {organism:'h_sapiens',organ:'lung', features: 'ITGA11, ITGB8, ITGB1, SDC3, ITGA5, ITGA7, ITGA1, TMPRSS6, SDC1, ITGB6, ITGA4, SDC2, DDR1, GP6, LAIR1, SDC4, EZR, CD93, TGFB1, COMP, BMP1'}
> await api.dotplot(dotplot_params)

Thanks,
Ying

**Comment by iosonofabio** [comment]
Solution for now is to plot only the ones we have but report everything.
