### ISSUE TITLE
Invalid genes in homologs query

### ISSUE THREAD

**Issue by YingX97** [fabilab/cell_atlas_approximations_API#29]
Hi Fabio:

Can you capture all the invalid genes for the homologs query? 
Q: "What are the homologs of COL1A1,CD19,CD20,HELLO,GP6 from human to mouse?"

> let api = require('@fabilab/atlasapprox')
> let params = {source_organism:'h_sapiens', features: 'COL1A1,CD19,CD20,HELLO,GP6', target_organism:'m_musculus'}
> await api.homologs(params)
Uncaught:
{
  status: 400,
  message: 'Feature could not be found: cd20.',
  error: {
    type: 'invalid_parameter',
    invalid_parameter: 'feature',
    invalid_value: 'cd20'
  }
}

**Comment by iosonofabio** [comment]
fixed, released soon
