### ISSUE TITLE
Internal server errror of fraction detected

### ISSUE THREAD

**Issue by YingX97** [fabilab/cell_atlas_approximations_API#5]
I am trying to get data for this intent:  "fraction_detected.geneExpression.across_organs" by making an API call: 
apiFraction = await atlasapprox.fraction_detected(organism, features, null, celltype, "gene_expression")

The fraction detected url doesn't work:
https://api.atlasapprox.org/v1/fraction_detected?organism=h_sapiens&features=TP53%2CAHR%2CMED4%2CVWF%2CCOL1A1%2CAPOE&celltype=fibroblast

However, it works well if I ask for average.

**Comment by iosonofabio** [comment]
Fixed in 932b0b5, it was a missing import. Will be in the next deployment.
