### ISSUE TITLE
Measurement type not found: chromatin_accessibility for similar cell types

### ISSUE THREAD

**Issue by YingX97** [fabilab/cell_atlas_approximations_API#6]
Failed API call on this url: https://api.atlasapprox.org/v1/similar_celltypes?organism=h_sapiens&organ=Lung&celltype=fibroblast&features=chr1:9955-10355&number=8&measurement_type=chromatin_accessibility

**Comment by iosonofabio** [comment]
Fixed in f12759b, which will be in the next deployment. It was a bunch of sloppy calls to get_organs and get_celltypes that defaulted to gene expression.
